### ISSUE TITLE
On the fly adding of products in an order

### ISSUE THREAD

**Issue by werthen** [ZeusWPI/Haldis#59] opened 2015-06-23 09:13 UTC

**Comment by feliciaan** [comment] 2015-06-23 09:13
Duplicate of #58

**Comment by Silox** [comment] 2015-06-23 09:14
This is not a duplicate; this would add the possibility to make the application more of a user-based effort instead of having to wait for an admin to add stuff to the app.

**Comment by mcbloch** [comment] 2020-12-09 21:56
With the new system of hlds files this is not possible via the UI. Modifying the hlds files is a piece of cake tho.

**Closed by mcbloch** 2020-12-09 21:56 UTC
